### ISSUE TITLE
Error Starting

### ISSUE THREAD

**Issue by bpatelTWO** [NeoxaChain/Neoxa#18]
I completed the install steps but when starting. I get the error below:

pool@neoxa:~/kawpow-pool$ node ./init.js
/home/pool/kawpow-pool/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/pool/kawpow-pool/node_modules/bignum/build/Release/bignum.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/home/pool/kawpow-pool/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/pool/kawpow-pool/node_modules/bignum/index.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by dogemackenzie** [comment]
did you get this going for yourself?
